# Generated by Django 5.2.17 on 2026-10-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptNo', models.AutoField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Address', models.CharField(max_length=200)),
                ('DeptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
