# Generated by Django 5.2.17 on 2026-10-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DeptNo',
            field=models.ForeignKey(db_column='DeptNo', on_delete=django.db.models.deletion.CASCADE, to='myapi.department'),
        ),
    ]
